env:
  browser: true
  es6: true
  node: true
  worker: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
globals:
  define: false
  Class: false
  log: false
  TRANSITIONEND: false
  _: false
  Detect: false
  Types: false
  Modernizr: false
  requestAnimFrame: false
  MozWebSocket: false
  $: false
  isInt: false
